Repository LDMX-Software/Ecal, pull requests merged in 2020-08, with the labels that each got.

#6 Update detector ID structure
  include/Ecal/EcalClusterProducer.h
  include/Ecal/EcalDigiProducer.h
  include/Ecal/EcalRecProducer.h
  include/Ecal/EcalSim2Rec.h
  include/Ecal/EcalVetoProcessor.h
  python/digi.py
  src/DNNEcalVetoProcessor.cxx
  src/EcalClusterProducer.cxx
  src/EcalDigiProducer.cxx
  src/EcalRecProducer.cxx
  src/EcalSim2Rec.cxx
  src/EcalVetoProcessor.cxx
  test/EcalDigiPipelineTest.cxx
Labels: cleanup, enhancement

#7 Pass ecal hex readout parameters from python
  include/Ecal/EcalSim2Rec.h
  python/digi.py
  python/ecalClusters.py
  python/vetos.py
  src/DNNEcalVetoProcessor.cxx
  src/EcalClusterProducer.cxx
  src/EcalRecProducer.cxx
  src/EcalSim2Rec.cxx
  src/EcalVetoProcessor.cxx
Labels: cleanup

#4 iss3: Update CMakeLists to make use of targets.
  CMakeLists.txt
Labels: build, cleanup, external
